# This is file of the project INGONG
# Licensed under the MIT License.
# Copyright (c) 2025 INGONG
# For full license text, see the LICENSE file in the root directory or at
# https://opensource.org/license/mit
# Author: Junho Kim
# Latest Updated Date: 2026-01-04

services:
  app-prod:
    build: . 
    container_name: inha_notice_nestjs
    restart: unless-stopped
    ports:
      # Only DSM accessible
      - "127.0.0.1:37821:3000"
    env_file:
      - .env
    volumes:
      - ./src/config/firebase-service-account.json:/app/dist/src/config/firebase-service-account.json:ro
      - ./database:/app/database
    environment:
      - NODE_ENV=production
      - TZ=Asia/Seoul
      - PORT=3000
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M