# This is file of the project inha_notice
# Licensed under the MIT License.
# Copyright (c) 2025-2026 INGONG
# For full license text, see the LICENSE file in the root directory or at
# https://opensource.org/license/mit
# Author: Junho Kim
# Latest Updated Date: 2026-02-18

services:
  app-prod:
    build: . 
    container_name: inha_notice_nestjs
    restart: unless-stopped
    ports:
      # Only DSM accessible
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    volumes:
      - ./src/config/firebase-service-account.json:/app/dist/src/config/firebase-service-account.json:ro
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - TZ=Asia/Seoul
      - PORT=3000
    networks:
      - inha_notice_network

networks:
  inha_notice_network:
    external: true
    name: inha_notice_network